# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Frontend.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.CameraWidget = QtWidgets.QWidget(self.centralwidget)
        self.CameraWidget.setGeometry(QtCore.QRect(30, 20, 351, 311))
        font = QtGui.QFont()
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.CameraWidget.setFont(font)
        self.CameraWidget.setAutoFillBackground(False)
        self.CameraWidget.setStyleSheet("background-color: rgb(225,220,220);")
        self.CameraWidget.setObjectName("CameraWidget")
        self.TurnCameraButton = QtWidgets.QPushButton(self.centralwidget)
        self.TurnCameraButton.setGeometry(QtCore.QRect(130, 340, 131, 31))
        self.TurnCameraButton.setObjectName("TurnCameraButton")
        self.TargetWidget = QtWidgets.QWidget(self.centralwidget)
        self.TargetWidget.setGeometry(QtCore.QRect(540, 50, 241, 221))
        self.TargetWidget.setStyleSheet("background-color: rgb(225,220,220);")
        self.TargetWidget.setObjectName("TargetWidget")
        self.TargetImagesLabel = QtWidgets.QLabel(self.centralwidget)
        self.TargetImagesLabel.setGeometry(QtCore.QRect(570, 15, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.TargetImagesLabel.setFont(font)
        self.TargetImagesLabel.setObjectName("TargetImagesLabel")
        self.horizontalSlider = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider.setGeometry(QtCore.QRect(540, 280, 191, 20))
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.spinBox = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox.setGeometry(QtCore.QRect(740, 280, 42, 22))
        self.spinBox.setObjectName("spinBox")
        self.CreateReportButton = QtWidgets.QPushButton(self.centralwidget)
        self.CreateReportButton.setGeometry(QtCore.QRect(590, 510, 181, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.CreateReportButton.setFont(font)
        self.CreateReportButton.setStyleSheet("background-color: rgb(225,220,220);")
        self.CreateReportButton.setObjectName("CreateReportButton")
        self.ExportPathLabel = QtWidgets.QLabel(self.centralwidget)
        self.ExportPathLabel.setGeometry(QtCore.QRect(130, 472, 641, 31))
        self.ExportPathLabel.setFrameShape(QtWidgets.QFrame.Panel)
        self.ExportPathLabel.setText("")
        self.ExportPathLabel.setObjectName("ExportPathLabel")
        self.SetExportPathButton = QtWidgets.QPushButton(self.centralwidget)
        self.SetExportPathButton.setGeometry(QtCore.QRect(20, 460, 101, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.SetExportPathButton.setFont(font)
        self.SetExportPathButton.setObjectName("SetExportPathButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        self.menuMenu = QtWidgets.QMenu(self.menubar)
        self.menuMenu.setObjectName("menuMenu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionLoad_target_images = QtWidgets.QAction(MainWindow)
        self.actionLoad_target_images.setObjectName("actionLoad_target_images")
        self.menuMenu.addAction(self.actionLoad_target_images)
        self.menubar.addAction(self.menuMenu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.TurnCameraButton.setText(_translate("MainWindow", "Camera ON/OFF"))
        self.TargetImagesLabel.setText(_translate("MainWindow", "Target images database"))
        self.CreateReportButton.setText(_translate("MainWindow", "Create target report"))
        self.SetExportPathButton.setText(_translate("MainWindow", "Set output path"))
        self.menuMenu.setTitle(_translate("MainWindow", "Menu"))
        self.actionLoad_target_images.setText(_translate("MainWindow", "Load target images"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
